server:
  port: 8080
  servlet:
    path: /

logging:
  level:
    cn.itcast: debug



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
     prefix: /templates/
     suffix: .html
    static-path-pattern: /**    #静态资源的请求方式

  thymeleaf:
    prefix: /templates/
    suffix: .html
    cache: false
#  web:
#    resources:
#      static-locations: classpath:/templates/

mybatis:
#  mapper-locations: mapper/*.xml
  type-aliases-package: cn.itcast.pojo
#  configuration:
#    map-underscore-to-camel-case: on

